name: CI

on:
    push:
        branches: [master]
        paths:
            - "src/**"
            - "tests/**"
            - "build/**"
    pull_request:
        branches: [master]
    workflow_dispatch:
permissions: write-all
jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: "ci-${{ github.head_ref || github.ref_name }}"
            cancel-in-progress: true
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v2
              with:
                  global-json-file: global.json

            - name: Tool Restore
              run: dotnet tool restore

            - name: Build
              run: dotnet nuke build --configuration Release

            - name: Lint
              run: dotnet nuke lint --skip build

            - name: Tests
              run: dotnet nuke test-coverage --configuration Release --skip build

            - name: Relatorio de Testes
              uses: dorny/test-reporter@v1.5.0
              with:
                  name: Relatorio de Testes
                  reporter: dotnet-trx
                  path: tests/**/test_result.xml

            - name: Coverage Report
              run: dotnet nuke generate-report generate-badges

            - name: Coverage monitor
              uses: slavcodev/coverage-monitor-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  coverage_path: TestReport/Clover.xml

            - uses: actions/upload-artifact@v3
              with:
                  name: test_report
                  path: ./TestReport

            - name: Lines of Code Badge
              uses: DeathSy/GHA-LoC-Badge@1.0.3
              with:
                  directory: ./
                  badge: ./Badges/lines_badge.svg
                  patterns: "**/*.fs|**/*.fsx|**/*.cs|**/*.ts|**/*.js"
                  ignore: "node_modules"

            - name: Publish Badges
              if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./Badges
                  publish_branch: badges
                  force_orphan: true
